name: harrypotter_magic_spells # ?? ? ???? ?? ? ?? (???? ???)
description: ???? ?? ??? ??? ???? ?? ? # ?? ? ???? ?? ? ??

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3 # ?? ? ???? ?? ? ?? (1.0.0+1? ??)

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  torch_light: ^1.1.0
  speech_to_text: ^7.0.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/image/
